version: "2.2"

services:
    postgres:
        image: postgres
        container_name: native_db
        restart: always
        environment:
            POSTGRES_PASSWORD: example
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./init:/docker-entrypoint-initdb.d/
            - ./data/postgres:/var/lib/postgresql

    api:
        image: wi4er/philister:0.0.2
        container_name: native_api
        restart: always
        ports:
            - "3000:3000"
        links:
            - postgres
            - cache
        environment:
            APP_PORT: 3000
            DB_HOST: postgres
            REDIS_URL: redis://cache:6379/

    web:
        image: node:lts
        container_name: native_web
        restart: always
        working_dir: /app
        command: npm start
        ports:
            - "3001:3000"
        links:
            - api
            - cache
        environment:
            APP_PORT: 3000
            REDIS_URL: redis://cache:6379/
        volumes:
            - .:/app

    frontend:
        image: nginx
        container_name: native_frontend
        ports:
            - "80:80"
        environment:
            - NGINX_PORT=80
        links:
            - api
            - web
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    cache:
        image: redis:alpine
        container_name: native_cache
        ports:
            - "6379:6379"